BEGIN TRANSACTION;

INSERT INTO category (id, title, parent, other)
VALUES
    ('men-casual', 'Casual', 'Men', 0),
    ('men-sports', 'Sports', 'Men', 0),
    ('men-formal', 'Formal', 'Men', 0),
    ('men-standard', 'Standard', 'Men', 0),
    ('men-t-shirts', 'T-Shirts', 'Men', 0),
    ('men-shirts', 'Shirts', 'Men', 0),
    ('men-jeans', 'Jeans', 'Men', 0),
    ('men-trousers', 'Trousers', 'Men', 0),
    ('men-sleep-wear', 'Sleep Wear', 'Men', 1),
    ('men-sandals', 'Sandals', 'Men', 1),
    ('men-loafers', 'Loafers', 'Men', 1),
    ('women-kurta-n-kurti', 'Kurta & Kurti', 'Women', 0),
    ('women-trousers', 'Trousers', 'Women', 0),
    ('women-casual', 'Casual', 'Women', 0),
    ('women-sports', 'Sports', 'Women', 0),
    ('women-formal', 'Formal', 'Women', 0),
    ('women-sarees', 'Sarees', 'Women', 0),
    ('women-shoes', 'Shoes', 'Women', 0),
    ('women-sleep-wear', 'Sleep Wear', 'Women', 1),
    ('women-sandals', 'Sandals', 'Women', 1),
    ('women-loafers', 'Loafers', 'Women', 1),
    ('women-rings', 'Rings', 'Women', 1),
    ('women-earrings', 'Earrings', 'Women', 1),
    ('women-jewellery-sets', 'Jewellery Sets', 'Women', 1),
    ('women-lockets', 'Lockets', 'Women', 1),
    ('women-jeans', 'Jeans', 'Women', 1),
    ('women-polo-t-shirts', 'Polo T-Shirts', 'Women', 1),
    ('women-skirts', 'SKirts', 'Women', 1),
    ('women-jackets', 'Jackets', 'Women', 1),
    ('women-tops', 'Tops', 'Women', 1),
    ('women-make-up', 'Make Up', 'Women', 1),
    ('women-hair-care', 'Hair Care', 'Women', 1),
    ('women-perfumes', 'Perfumes', 'Women', 1),
    ('women-skin-care', 'Skin Care', 'Women', 1),
    ('women-hand-bags', 'Hand Bags', 'Women', 1),
    ('women-single-bags', 'Single Bags', 'Women', 1),
    ('women-travel-bags', 'Travel Bags', 'Women', 1),
    ('women-wallets-n-belts', 'Wallets & Belts', 'Women', 1),
    ('women-sunglases', 'Sunglases', 'Women', 1),
    ('women-nail', 'Nail', 'Women', 1),
    ('kids-casual', 'Casual', 'Kids', 0),
    ('kids-sports', 'Sports', 'Kids', 0),
    ('kids-formal', 'Formal', 'Kids', 0),
    ('kids-standard', 'Standard', 'Kids', 0),
    ('kids-t-shirts', 'T-Shirts', 'Kids', 0),
    ('kids-shirts', 'Shirts', 'Kids', 0),
    ('kids-jeans', 'Jeans', 'Kids', 0),
    ('kids-trousers', 'Trousers', 'Kids', 0),
    ('kids-sleep-wear', 'Sleep Wear', 'Kids', 1),
    ('kids-sandals', 'Sandals', 'Kids', 1),
    ('kids-loafers', 'Loafers', 'Kids', 1),
    ('digital-camera', 'Camera', 'Digital', 0),
    ('digital-mobile', 'Mobile', 'Digital', 0),
    ('digital-tablet', 'Tablet', 'Digital', 0),
    ('digital-laptop', 'Laptop', 'Digital', 0),
    ('digital-accesories', 'Accesories', 'Digital', 1);

COMMIT TRANSACTION;
